Add support for cortex m4, improved testing

diff --git a/build b/build
--- a/build
+++ b/build
@@ -178,11 +178,26 @@ function check_build_state() {
     fi
 }
 
+# Initial setup
+function setup_variables() {
+    # Colors
+    BOLD="\033[1m"
+    RED="\033[01;31m"
+    RST="\033[0m"
+    YLW="\033[01;33m"
+    GRN="\033[1;32m"
+
+    JOBS="-j$(($(nproc --all) + 1))"
+
+    # Start of script
+    START=$(date +%s)
+}
+
 function setup_environment() {
-    ROOT=${PWD}
-    PREBUILTS_BIN=${ROOT}/prebuilts/bin
-    INSTALL=${ROOT}/${TARGET}
-    SOURCES_DIR=${ROOT}/sources
+    ROOT="${PWD}"
+    PREBUILTS_BIN="${ROOT}/prebuilts/bin"
+    INSTALL="${ROOT}/${TARGET}"
+    SOURCES_DIR="${ROOT}/sources"
     BUILD_STATE_DIR="${ROOT}/state"
     BUILD_DIR="${ROOT}/build_dir"
 
@@ -194,24 +209,6 @@ function setup_environment() {
     mkdir -p ${SOURCES_DIR}
     mkdir -p ${BUILD_STATE_DIR}
 }
-
-# Initial setup
-function setup_variables() {
-    # Colors
-    BOLD="\033[1m"
-    RED="\033[01;31m"
-    RST="\033[0m"
-    YLW="\033[01;33m"
-    GRN="\033[1;32m"
-
-    # Configuration variables
-    CONFIGURATION=( "--disable-multilib" "--disable-werror" )
-    JOBS="-j$(($(nproc --all) + 1))"
-
-    # Start of script
-    START=$(date +%s)
-}
-
 
 # Parse parameters
 function parse_parameters() {
@@ -243,14 +240,17 @@ function parse_parameters() {
     case "${ARCH}" in
         "arm") TARGET="arm-linux-gnueabi" ;;
         "arm64") TARGET="aarch64-linux-gnu" ;;
-        "i686") TARGET="i686-linux-gnu" ;;
+        "x86") TARGET="i686-linux-gnu" ;;
         "x86_64") TARGET="x86_64-linux-gnu" ;;
+        "cm4") TARGET="arm-none-eabi" ;;
         *) die "Absent or invalid arch specified!" -h ;;
     esac
 
+    setup_environment
+
     if [[ -z ${TARBALLS} ]]; then
         # Search for a valid target config
-        type -t config_${TARGET}_${SOURCE}_${VERSION}_git > /dev/null || die "No git config found for ${TARGET}!"
+        type -t config_${TARGET} > /dev/null || die "No git config found for ${TARGET}!"
         config_${TARGET} ${SOURCE} ${VERSION} git
     else
         # Search for a valid target config
@@ -263,7 +263,9 @@ function parse_parameters() {
 function build_binaries() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     local AXEL=${ROOT}/sources/axel
     [[ ! -d ${AXEL} ]] && git -C "$(dirname "${AXEL}")" clone --depth=1 https://github.com/axel-download-accelerator/axel
@@ -298,19 +300,28 @@ function build_binaries() {
 function download_sources() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     cd ${SOURCES_DIR} || die "Failed to create sources directory!"
 
     if [[ -z ${TARBALLS} ]]; then
-        if [[ ! -d glibc-${GLIBC} ]]; then
-            header "DOWNLOADING GLIBC"
-            git_clone ${GLIBC_GIT_URL} glibc-${GLIBC} -b ${GLIBC}
-        fi
+        if [[ "${IS_BARE_METAL}" = true ]]; then
+            if [[ ! -d newlib-${NEWLIB} ]]; then
+                header "DOWNLOADING NEWLIB"
+                git_clone ${NEWLIB_GIT_URL} newlib-${NEWLIB} -b ${NEWLIB}
+            fi
+        else
+            if [[ ! -d glibc-${GLIBC} ]]; then
+                header "DOWNLOADING GLIBC"
+                git_clone ${GLIBC_GIT_URL} glibc-${GLIBC} -b ${GLIBC}
+            fi
 
-        if [[ ! -d linux-${LINUX} ]]; then
-            header "DOWNLOADING LINUX KERNEL"
-            git_clone ${LINUX_GIT_URL} linux-${LINUX} -b ${LINUX}
+            if [[ ! -d linux-${LINUX} ]]; then
+                header "DOWNLOADING LINUX KERNEL"
+                git_clone ${LINUX_GIT_URL} linux-${LINUX} -b ${LINUX}
+            fi
         fi
 
         if [[ ! -d binutils-${BINUTILS} ]]; then
@@ -323,14 +334,22 @@ function download_sources() {
             git_clone ${GCC_GIT_URL} gcc-${GCC} -b ${GCC}
         fi
     else
-        if [[ ! -f ${GLIBC}.tar.xz ]]; then
-            header "DOWNLOADING GLIBC"
-            axel ${GLIBC_BASE_URL}${GLIBC}.tar.xz
-        fi
+        if [[ "${IS_BARE_METAL}" = true ]]; then
+            if [[ ! -f ${NEWLIB}.tar.gz ]]; then
+                die "${NEWLIB}.tar.xz"
+                header "DOWNLOADING NEWLIB"
+                axel ${NEWLIB_BASE_URL}${NEWLIB}.tar.gz
+            fi
+        else        
+            if [[ ! -f ${GLIBC}.tar.xz ]]; then
+                header "DOWNLOADING GLIBC"
+                axel ${GLIBC_BASE_URL}${GLIBC}.tar.xz
+            fi
 
-        if [[ ! -f linux-${LINUX}.tar.xz ]]; then
-            header "DOWNLOADING LINUX KERNEL"
-            axel ${LINUX_BASE_URL}${LINUX}.tar.xz
+            if [[ ! -f linux-${LINUX}.tar.xz ]]; then
+                header "DOWNLOADING LINUX KERNEL"
+                axel ${LINUX_BASE_URL}${LINUX}.tar.xz
+            fi
         fi
 
         if [[ ! -f binutils-${BINUTILS}.tar.xz ]]; then
@@ -340,7 +359,7 @@ function download_sources() {
 
         if [[ ! -f ${GCC}.tar.gz ]]; then
             header "DOWNLOADING GCC"
-            axel ${GCC_BASE_URL}/${GCC}/${GCC}.tar.gz
+            axel ${GCC_BASE_URL}${GCC}.tar.gz
         fi
     fi
 
@@ -373,7 +392,9 @@ function download_sources() {
 function extract_sources() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "EXTRACTING DOWNLOADED TARBALLS"
 
@@ -385,8 +406,12 @@ function extract_sources() {
     extract ${ISL}.tar.xz ${SOURCES_DIR}/isl-${ISL}
 
     if [[ -n ${TARBALLS} ]]; then
-        extract ${GLIBC}.tar.xz ${SOURCES_DIR}/glibc-${GLIBC}
-        extract linux-${LINUX}.tar.xz ${SOURCES_DIR}/linux-${LINUX}
+        if [[ "${IS_BARE_METAL}" = true ]]; then
+            extract ${NEWLIB}.tar.gz ${SOURCES_DIR}/newlib-${NEWLIB}
+        else    
+            extract ${GLIBC}.tar.xz ${SOURCES_DIR}/glibc-${GLIBC}
+            extract linux-${LINUX}.tar.xz ${SOURCES_DIR}/linux-${LINUX}
+        fi
         extract binutils-${BINUTILS}.tar.xz ${SOURCES_DIR}/binutils-${BINUTILS}
         extract ${GCC}.tar.gz ${SOURCES_DIR}/gcc-${GCC}
     fi
@@ -399,15 +424,14 @@ function extract_sources() {
 function build_binutils() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "BUILDING BINUTILS"
     mkdir -p ${BUILD_DIR}/build-binutils
     cd ${BUILD_DIR}/build-binutils
-    ${SOURCES_DIR}/binutils-${BINUTILS}/configure "${CONFIGURATION[@]}" \
-                          --target=${TARGET} \
-                          --prefix="${INSTALL}" \
-                          --disable-gdb
+    ${SOURCES_DIR}/binutils-${BINUTILS}/configure "${BINUTILS_CONFIGURATION[@]}"
     make ${JOBS} || die "Error while building binutils!" -n
     make install ${JOBS} || die "Error while installing binutils!" -n
 
@@ -420,6 +444,8 @@ function build_headers() {
 
     check_build_state ${FUNCNAME[0]} && return
     cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "MAKING LINUX HEADERS"
     cd ${SOURCES_DIR}/linux-${LINUX} || die "Linux kernel folder does not exist!"
@@ -436,6 +462,8 @@ function build_gcc() {
 
     check_build_state ${FUNCNAME[0]} && return
     cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "MAKING GCC"
 
@@ -446,12 +474,31 @@ function build_gcc() {
 
     mkdir -p ${BUILD_DIR}/build-gcc
     cd ${BUILD_DIR}/build-gcc || die "GCC build folder does not exist!"
-    ${SOURCES_DIR}/gcc-${GCC}/configure "${CONFIGURATION[@]}" \
-                     --enable-languages=c \
-                     --target=${TARGET} \
-                     --prefix=${INSTALL}
+    ${SOURCES_DIR}/gcc-${GCC}/configure "${GCC_CONFIGURATION[@]}"
     make all-gcc ${JOBS} || die "Error while building gcc!" -n
     make install-gcc ${JOBS} || die "Error while installing gcc!" -n
+ 
+    set_build_state ${FUNCNAME[0]}
+}
+
+
+# Build newlib
+function build_newlib() {
+
+    check_build_state ${FUNCNAME[0]} && return
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
+
+    header "MAKING NEWLIB"
+
+    which arm-none-eabi-ranlib
+
+    mkdir -p ${BUILD_DIR}/build-newlib
+    cd ${BUILD_DIR}/build-newlib || die "newlib build folder does not exist!"
+    ${SOURCES_DIR}/newlib-${NEWLIB}/configure "${NEWLIB_CONFIGURATION[@]}"
+    make all || die "Error while building newlib!" -n
+    make install || die "Error while installing newlib!" -n
  
     set_build_state ${FUNCNAME[0]}
 }
@@ -462,16 +509,13 @@ function build_glibc() {
 
     check_build_state ${FUNCNAME[0]} && return
     cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "MAKING GLIBC"
     mkdir -p ${BUILD_DIR}/build-glibc
     cd ${BUILD_DIR}/build-glibc || die "glibc build folder does not exist!"
-    ${SOURCES_DIR}/glibc-${GLIBC}/configure --prefix="${INSTALL}/${TARGET}" \
-                          --build="${MACHTYPE}" \
-                          --host=${TARGET} \
-                          --target=${TARGET} \
-                          --with-headers="${INSTALL}/${TARGET}/include" \
-                          "${CONFIGURATION[@]}" libc_cv_forced_unwind=yes
+    ${SOURCES_DIR}/glibc-${GLIBC}/configure "${GLIBC_CONFIGURATION[@]}"
     make install-bootstrap-headers=yes install-headers ${JOBS} || die "Error installing headers for glibc!" -n
     make csu/subdir_lib ${JOBS} || die "Error while making subdir_lib for glibc!" -n
     install csu/crt1.o csu/crti.o csu/crtn.o "${INSTALL}/${TARGET}/lib"
@@ -490,11 +534,28 @@ function build_glibc() {
 }
 
 
+configure_gcc_stage_2() {
+    check_build_state ${FUNCNAME[0]} && return
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
+
+    header "CONFIGURING GCC STAGE 2"
+
+    cd ${BUILD_DIR}/build-gcc || die "GCC build folder does not exist!"
+    ${SOURCES_DIR}/gcc-${GCC}/configure "${GCC_STAGE_2_CONFIGURATION[@]}"
+ 
+    set_build_state ${FUNCNAME[0]}
+}
+
+
 # Install GCC
 function install_gcc() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     header "INSTALLING GCC"
     cd ${BUILD_DIR}/build-gcc || die "GCC build folder does not exist!"
@@ -509,7 +570,9 @@ function install_gcc() {
 function package_tc() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     if [[ -n ${COMPRESSION} ]]; then
         PACKAGE=${TARGET}-${VERSION}.x-${SOURCE}-$(TZ=UTC date +%Y%m%d).tar.${COMPRESSION}
@@ -538,7 +601,9 @@ function package_tc() {
 function ending_info() {
 
     check_build_state ${FUNCNAME[0]} && return
-    cd ${ROOT}    
+    cd ${ROOT}
+    # use clean hashtable
+    hash -r
 
     END=$(date +%s)
 
@@ -568,14 +633,24 @@ function ending_info() {
 
 parse_parameters "${@}"
 setup_variables
-setup_environment
 build_binaries
 download_sources
 extract_sources
-build_binutils
-build_headers
-build_gcc
-build_glibc
-install_gcc
+
+if [[ "${IS_BARE_METAL}" = true ]]; then
+    build_binutils    
+    build_gcc
+    build_newlib
+    # FIXME: check if this is a generic step
+    configure_gcc_stage_2
+    install_gcc
+else
+    build_binutils
+    build_headers
+    build_gcc
+    build_glibc
+    install_gcc
+fi
+
 package_tc
 ending_info
